-- 코드를 입력하세요
SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS AS I
LEFT OUTER JOIN ANIMAL_OUTS AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.ANIMAL_ID is NULL
ORDER BY I.DATETIME
LIMIT 3
# DATE_FORMAT(I.DATETIME, "%Y-%m-%d %HH-%mm-%ss")